### ISSUE TITLE
panicked at 'assertion failed: self.buffer.len() >= len + size_of::<u32>()', src/sap.rs:77:9

### ISSUE THREAD

**Issue by axellerdaolberg** [mephesto1337/saprouter2socks#1]
Hi Mephesto1337,

Im testing you project in my lab and see that at use the firefox as socks5 clients, the HTTPS fail with the error message SSL_ERROR_RX_RECORD_TOO_LONG and the running command into the server return:

irout.cpp8240RTPENDLIST::timeoutPend: could not establish connection within 5s (ROUTED)Mon Sep 11 12:12:02 202384SAProuter 40.4 on 'dave'*ERR*
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.buffer.len() >= len + size_of::<u32>()', src/sap.rs:77:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.buffer.len() >= len + size_of::<u32>()', src/sap.rs:77:9

The machine its an LXC container with Ubuntu 22.04 LTS.

Could you please help me?
Thanks in advance,

Axel

**Comment by mephesto1337** [comment]
Hello,

I think I identified the issue in the code.
Unfortunately I cannot test it my self, please use the [issue-1](https://github.com/mephesto1337/saprouter2socks/tree/issue-1) branch to test the fix.
I will merge it once you confirmed it actually works.

Regards,
